#include "korvo_web.h"
#include "korvo_network.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "esp_app_desc.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

static const char *TAG="korvo_web"; static httpd_handle_t s_server;
#define ADMIN_USER "admin"
#define ADMIN_PASS "password"
#define COOKIE "KORVO_SESSION=korvo_admin"
static const char *STYLE="<style>*{box-sizing:border-box}body{margin:0;background:#10151b;color:#e9eef4;font-family:Arial}.top{background:#171f28;padding:18px 24px}.wrap{max-width:900px;margin:24px auto;padding:0 16px}.card{background:#18212b;border:1px solid #34404d;border-radius:10px;padding:20px;margin-bottom:18px}a{color:#8ecbff;text-decoration:none;margin-right:18px}label{display:block;margin:13px 0 5px;color:#aebac6}input{width:100%;padding:11px;border:1px solid #445363;border-radius:6px;background:#0f151b;color:white}input[type=checkbox]{width:auto}.btn{margin-top:18px;padding:11px 18px;border:0;border-radius:6px;font-weight:bold}.grid{display:grid;grid-template-columns:180px 1fr;gap:9px 14px}.mono{font-family:monospace}.ok{color:#74d680}.small{font-size:13px;color:#9eabb8}</style>";
static bool auth(httpd_req_t*r){size_t n=httpd_req_get_hdr_value_len(r,"Cookie");if(!n||n>255)return false;char b[256];return httpd_req_get_hdr_value_str(r,"Cookie",b,sizeof(b))==ESP_OK&&strstr(b,COOKIE);}
static esp_err_t redir(httpd_req_t*r,const char*p){httpd_resp_set_status(r,"303 See Other");httpd_resp_set_hdr(r,"Location",p);return httpd_resp_send(r,NULL,0);}
static bool guard(httpd_req_t*r){if(auth(r))return true;redir(r,"/login");return false;}
static void decode(char*d,size_t z,const char*s){size_t i=0;while(*s&&i+1<z){if(*s=='%'&&s[1]&&s[2]){char h[3]={s[1],s[2],0};d[i++]=(char)strtol(h,NULL,16);s+=3;}else if(*s=='+'){d[i++]=' ';s++;}else d[i++]=*s++;}d[i]=0;}
static bool val(const char*b,const char*k,char*o,size_t z){size_t kl=strlen(k);const char*p=b;while(p&&*p){if((p==b||p[-1]=='&')&&!strncmp(p,k,kl)&&p[kl]=='='){p+=kl+1;const char*e=strchr(p,'&');size_t n=e?(size_t)(e-p):strlen(p);char x[160];if(n>=sizeof(x))n=sizeof(x)-1;memcpy(x,p,n);x[n]=0;decode(o,z,x);return true;}p=strchr(p,'&');if(p)p++;}return false;}
static esp_err_t body(httpd_req_t*r,char*b,size_t z){if(r->content_len<=0||(size_t)r->content_len>=z)return ESP_ERR_INVALID_SIZE;int n=0;while(n<r->content_len){int x=httpd_req_recv(r,b+n,r->content_len-n);if(x<=0)return ESP_FAIL;n+=x;}b[n]=0;return ESP_OK;}
static void head(httpd_req_t*r,const char*t){char b[160];httpd_resp_set_type(r,"text/html");httpd_resp_sendstr_chunk(r,"<!doctype html><html><head><meta name=viewport content='width=device-width,initial-scale=1'>");httpd_resp_sendstr_chunk(r,STYLE);snprintf(b,sizeof(b),"<title>KORVO - %s</title></head><body>",t);httpd_resp_sendstr_chunk(r,b);httpd_resp_sendstr_chunk(r,"<div class=top><b>KORVO</b> &nbsp; <a href='/'>ESTADO</a><a href='/network'>RED</a><a href='/logout'>SALIR</a></div><div class=wrap>");}
static void foot(httpd_req_t*r){httpd_resp_sendstr_chunk(r,"</div></body></html>");httpd_resp_sendstr_chunk(r,NULL);}
static esp_err_t login_g(httpd_req_t*r){httpd_resp_set_type(r,"text/html");httpd_resp_sendstr_chunk(r,"<!doctype html><html><head><meta name=viewport content='width=device-width,initial-scale=1'>");httpd_resp_sendstr_chunk(r,STYLE);httpd_resp_sendstr_chunk(r,"</head><body><div class=top><b>KORVO</b></div><div class=wrap><div class=card><h2>Administracion</h2><form method=post action=/login><label>Usuario</label><input name=user><label>Clave</label><input name=pass type=password><button class=btn>ENTRAR</button></form></div></div></body></html>");return httpd_resp_sendstr_chunk(r,NULL);}
static esp_err_t login_p(httpd_req_t*r){char b[256],u[64]={0},p[64]={0};if(body(r,b,sizeof(b))!=ESP_OK||!val(b,"user",u,sizeof(u))||!val(b,"pass",p,sizeof(p)))return httpd_resp_send_err(r,HTTPD_400_BAD_REQUEST,"Solicitud invalida");if(strcmp(u,ADMIN_USER)||strcmp(p,ADMIN_PASS)){httpd_resp_set_status(r,"401 Unauthorized");return httpd_resp_sendstr(r,"Usuario o clave incorrectos");}httpd_resp_set_hdr(r,"Set-Cookie",COOKIE "; Path=/; HttpOnly; SameSite=Strict");return redir(r,"/");}
static esp_err_t logout_g(httpd_req_t*r){httpd_resp_set_hdr(r,"Set-Cookie","KORVO_SESSION=; Path=/; Max-Age=0");return redir(r,"/login");}
static esp_err_t status_g(httpd_req_t*r){if(!guard(r))return ESP_OK;korvo_network_status_t s;korvo_network_get_status(&s);const esp_app_desc_t*a=esp_app_get_description();char m[24],b[1100];snprintf(m,sizeof(m),"%02X:%02X:%02X:%02X:%02X:%02X",s.mac[0],s.mac[1],s.mac[2],s.mac[3],s.mac[4],s.mac[5]);head(r,"Estado");snprintf(b,sizeof(b),"<div class=card><h2>Estado</h2><div class=grid><div>Equipo</div><div><b>KORVO</b></div><div>Firmware</div><div class=mono>%s</div><div>Uptime</div><div>%llu s</div><div>Wi-Fi AP</div><div class=ok>ACTIVO</div><div>SSID</div><div class=mono>%s</div><div>Visible</div><div>%s</div><div>IP KORVO</div><div class=mono>%s</div><div>Gateway ESP32</div><div class=mono>%s</div><div>Clientes</div><div>%u</div><div>MAC</div><div class=mono>%s</div></div></div>",a?a->version:"--",(unsigned long long)(esp_timer_get_time()/1000000ULL),s.config.ssid,s.config.ssid_visible?"SI":"NO",s.config.ip,s.config.gateway_node_ip,(unsigned)s.connected_clients,m);httpd_resp_sendstr_chunk(r,b);foot(r);return ESP_OK;}
static esp_err_t net_g(httpd_req_t*r){if(!guard(r))return ESP_OK;korvo_network_config_t c;korvo_network_get_config(&c);char b[1900];head(r,"Red");snprintf(b,sizeof(b),"<div class=card><h2>Red privada KORVO</h2><p>KORVO = Access Point. Gateway ESP32 = Station.</p><form method=post action=/network><label>SSID</label><input name=ssid maxlength=32 value='%s'><label><input type=checkbox name=visible value=1 %s> SSID visible</label><label>Clave Wi-Fi</label><input name=password type=password maxlength=63 value='%s'><label>IP KORVO</label><input name=ip maxlength=15 value='%s'><label>Mascara</label><input name=netmask maxlength=15 value='%s'><label>IP Gateway ESP32</label><input name=gateway maxlength=15 value='%s'><button class=btn>GUARDAR Y REINICIAR</button></form><p class=small>Fabrica: korvo_wifi / 192.168.5.50 / Gateway 192.168.5.51</p></div><div class=card><form method=post action=/factory-network><button class=btn>RESTAURAR RED DE FABRICA</button></form></div>",c.ssid,c.ssid_visible?"checked":"",c.password,c.ip,c.netmask,c.gateway_node_ip);httpd_resp_sendstr_chunk(r,b);foot(r);return ESP_OK;}
static esp_err_t net_p(httpd_req_t*r){if(!guard(r))return ESP_OK;char b[640],x[128];if(body(r,b,sizeof(b))!=ESP_OK)return httpd_resp_send_err(r,HTTPD_400_BAD_REQUEST,"Solicitud invalida");korvo_network_config_t c;korvo_network_get_config(&c);if(val(b,"ssid",x,sizeof(x)))strlcpy(c.ssid,x,sizeof(c.ssid));if(val(b,"password",x,sizeof(x)))strlcpy(c.password,x,sizeof(c.password));if(val(b,"ip",x,sizeof(x)))strlcpy(c.ip,x,sizeof(c.ip));if(val(b,"netmask",x,sizeof(x)))strlcpy(c.netmask,x,sizeof(c.netmask));if(val(b,"gateway",x,sizeof(x)))strlcpy(c.gateway_node_ip,x,sizeof(c.gateway_node_ip));c.ssid_visible=strstr(b,"visible=1")!=NULL;if(korvo_network_save_config(&c)!=ESP_OK)return httpd_resp_send_err(r,HTTPD_400_BAD_REQUEST,"Configuracion invalida");httpd_resp_sendstr(r,"<html><body><h2>KORVO</h2><p>Configuracion guardada. Reiniciando...</p></body></html>");vTaskDelay(pdMS_TO_TICKS(700));esp_restart();return ESP_OK;}
static esp_err_t factory_p(httpd_req_t*r){if(!guard(r))return ESP_OK;if(korvo_network_factory_defaults()!=ESP_OK)return httpd_resp_send_err(r,HTTPD_500_INTERNAL_SERVER_ERROR,"Error restaurando red");httpd_resp_sendstr(r,"Red restaurada. Reiniciando...");vTaskDelay(pdMS_TO_TICKS(700));esp_restart();return ESP_OK;}
esp_err_t korvo_web_start(void){if(s_server)return ESP_OK;httpd_config_t c=HTTPD_DEFAULT_CONFIG();c.max_uri_handlers=10;c.lru_purge_enable=true;c.stack_size=8192;esp_err_t e=httpd_start(&s_server,&c);if(e!=ESP_OK)return e;const httpd_uri_t u[]={{.uri="/",.method=HTTP_GET,.handler=status_g},{.uri="/login",.method=HTTP_GET,.handler=login_g},{.uri="/login",.method=HTTP_POST,.handler=login_p},{.uri="/logout",.method=HTTP_GET,.handler=logout_g},{.uri="/network",.method=HTTP_GET,.handler=net_g},{.uri="/network",.method=HTTP_POST,.handler=net_p},{.uri="/factory-network",.method=HTTP_POST,.handler=factory_p}};for(size_t i=0;i<sizeof(u)/sizeof(u[0]);i++){e=httpd_register_uri_handler(s_server,&u[i]);if(e!=ESP_OK){httpd_stop(s_server);s_server=NULL;return e;}}ESP_LOGI(TAG,"Web admin ready");return ESP_OK;}
esp_err_t korvo_web_stop(void){if(!s_server)return ESP_OK;esp_err_t e=httpd_stop(s_server);s_server=NULL;return e;}
